theme:
 - osuny-campus-art-mediterrannee-footer
 - osuny
_merge: deep
params:
  debug:
    active: false
    productionUrl: "https://www.campusartmediterranee.fr"
  summary:
    position: hero
  search:
    active: true
  logo:
    header: '/assets/images/logo.svg'
    footer: '/assets/images/logo-white.svg'
  home:
    head:
      title: site
  blocks:
    ignored:
      - block-class-in-hero
      - block-class-footer-gallery
  events:
    index:
      highlight_exhibitions:
        future:
          options:
            image: true
    list:
      with_more: true
  organizations:
    prefer_image_over_logo: true
    single:
      backlinks: true
  pages:
    single:
      taxonomies:
        position: hero
    index:
      options:
        categories: true
  persons:
    single:
      backlinks: true
  projects:
    single:
      taxonomies:
        position: hero
        show_name: false
    share_links:
      enabled: false
  image_sizes:
    blocks:
      chapter:
        desktop:  838
    sections:
      home:
        hero:
          mobile:   864
          desktop:  1920
      pages:
        item:
          desktop:  864
        layouts:
          grid:
            desktop: 838
      posts:
        item:
          desktop:  864
      organizations:
        item:
          desktop:  864
      events:
        layouts:
          agenda:
            tablet:   539
            desktop:  539
          parent:
            tablet:   539
            desktop:  539
          list:
            mobile: 327
            tablet: 539
            desktop: 539
